<a href="https://colab.research.google.com/github/Muizza13/C-programs/blob/main/SentimentAnalysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd
import sklearn
from sklearn.feature_extraction.text import CountVectorizer

In [ ]:
X_text=['This is my new bookshelf',
        'I really like it',
        'The old one got damaged',
        'This is very pretty',
        'I threw away the old one']
Y_text=['positive', 'positive', 'negative', 'positive', 'negative']

In [ ]:
vectorizer=CountVectorizer()

In [ ]:
vectorizer.fit(X_text)

CountVectorizer()

In [ ]:
vocab=vectorizer.get_feature_names_out()
vocab

array(['away', 'bookshelf', 'damaged', 'got', 'is', 'it', 'like', 'my',
       'new', 'old', 'one', 'pretty', 'really', 'the', 'this', 'threw',
       'very'], dtype=object)

In [ ]:
X_term_doc_matrix=vectorizer.transform(X_text)
X_term_doc_matrix.toarray()

array([[0, 1, 0, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 1, 0]])

In [ ]:
df=pd.DataFrame(data=X_term_doc_matrix.toarray(),columns=vocab)
df

,away,bookshelf,damaged,got,is,it,like,my,new,old,one,pretty,really,the,this,threw,very
0,0,1,0,0,1,0,0,1,1,0,0,0,0,0,1,0,0
1,0,0,0,0,0,1,1,0,0,0,0,0,1,0,0,0,0
2,0,0,1,1,0,0,0,0,0,1,1,0,0,1,0,0,0
3,0,0,0,0,1,0,0,0,0,0,0,1,0,0,1,0,1
4,1,0,0,0,0,0,0,0,0,1,1,0,0,1,0,1,0

In [ ]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
le.fit(Y_text)
y=le.transform(Y_text)

In [ ]:
import sklearn
from sklearn.linear_model import LogisticRegression

In [ ]:
model=LogisticRegression()
X=X_term_doc_matrix
clf=model.fit(X,y)

In [ ]:
test=['like and pretty']
test_vector=vectorizer.transform(test)
print(test_vector.toarray())
df=pd.DataFrame(data=test_vector.toarray(),columns=vocab)
df

[[0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0]]

,away,bookshelf,damaged,got,is,it,like,my,new,old,one,pretty,really,the,this,threw,very
0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0

In [ ]:
df

,away,bookshelf,damaged,got,is,it,like,my,new,old,one,pretty,really,the,this,threw,very
0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0

In [ ]:
pred=clf.predict(test_vector)
print(pred)
print(le.inverse_transform(pred))

[1]
['positive']

In [ ]:
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report

In [ ]:
test_sample=X_term_doc_matrix
true=y
pred= [1, 1, 1, 0, 0]
acc=accuracy_score(true, pred)
cm=confusion_matrix(true, pred)
print('accuracy=', acc)
print('Confusion Matrix/n', cm)
print(classification_report(true, pred))

accuracy= 0.6
Confusion Matrix/n [[1 1]
 [1 2]]
              precision    recall  f1-score   support

           0       0.50      0.50      0.50         2
           1       0.67      0.67      0.67         3

    accuracy                           0.60         5
   macro avg       0.58      0.58      0.58         5
weighted avg       0.60      0.60      0.60         5